storeproject/store/urls.py
from django.urls import path
from .views import home, creators, creator, login_view, logout_view, register_view, info_view, videos

urlpatterns = [
    path('home/', home, name='store-home'),
    path('creators/', creators, name='store-creators'),
    path('creator/<int:pk>/', creator, name='store-creator'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('info/', info_view, name='store-info'),
    path('videos/', videos, name = 'store-videos'),
]

app_name = 'store'

storeproject/storeproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include ('store.urls', namespace='store')),
]

storeproject/store/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ['name']
        verbose_name = 'Category'
        verbose_name = 'Categories'

    def __str__(self):
        return f"{self.name}"


class Creator(models.Model):
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=13)
    country = models.CharField(max_length=100)

    class Meta:
        ordering = ['name']
        verbose_name = 'Creator'
        verbose_name_plural = 'Creators'

    def __str__(self):
        return f"{self.name} - {self.phone_number}, {self.country}"

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    amount = models.DecimalField(max_digits=8, decimal_places=2)

    product_category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True,
                                         related_name='products')
    creator = models.ForeignKey(Creator, on_delete=models.SET_NULL, null=True, blank=True,
                                         related_name='products')

    class Meta:
        ordering = ['name']
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return f"{self.name} {self.product_category} {self.price} {self.creator} {self.amount}"





storeproject/store/forms.py
from django import forms
from django.contrib.auth.models import User

class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repeat password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["username"]

    def clean(self):
        cleaned_data = super().clean()
        p1 = cleaned_data.get("password")
        p2 = cleaned_data.get("password2")

        if p1 and p2 and p1 != p2:
            raise forms.ValidationError("Passwords do not match!")

        return cleaned_data

class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)

storeproject/store/views.py
from django.http import HttpResponse
from .models import Creator
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import RegisterForm, LoginForm


def home(request):
    #return HttpResponse('Привіт це мій перший views!')
    return render(request, 'home.html')

def creators(request):
    creators_obj = Creator.objects.all()
    #return HttpResponse(creators_obj)
    context = {'creators': creators_obj}
    return render(request, 'creators.html', context)

def creator(request, pk):
    creators_obj = Creator.objects.filter(id=pk).first()
    #return HttpResponse(creators_obj)
    context = {'creator': creators_obj}
    return render(request, 'creator.html', context)

def info_view(request):
    return render(request, 'info.html')

def videos(request):
    return render(request, 'videos.html')

def register_view(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return redirect('school:login')
    else:
        form = RegisterForm()

    return render(request, 'register.html', {'form': form})

def login_view(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('store:store-home')  # змінити на вашу сторінку
            else:
                return render(request, 'login.html', {
                    'form': form,
                    'error': 'Невірний логін або пароль'
                })
    else:
        form = LoginForm()

    return render(request, 'login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('store:login')

storeproject/store/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}This is my first webpage.{% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/site.css' %}" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
            <a class=".text-primary btn btn-outline-primary" href="/store/home/">Головна сторінка</a>
            <a class=".text-success btn btn-outline-success" href="/store/creators/">Виробники</a>
            <a class=".text-danger btn btn-outline-danger" href="/store/creator/1/">Головний розробник магазину</a>
            <a class=".text-warning btn btn-outline-warning" href="/store/info/">Шаблон для допомоги на сайті</a>
            <a class=".text-danger btn btn-outline-danger" href="/store/videos/">Шаблон де можна подивитися відосики</a>
            </div>
        </nav>
    </header>
    <hr>
    <main>
        {% block content %}{% endblock %}
    </main>
    <hr>
    <footer>
        <p class="">© 2025</p>
    </footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

storeproject/store/templates/creator.html
{% extends 'base.html' %}

{% block title %}{{ creator }}{% endblock %}

{% block content %}
<div class="text-danger">
<h2>{{ creator }}</h2>
<a href="/store/creators/" class="text-danger">← Назад до списку</a>
</div>
{% endblock %}

storeproject/store/templates/creators.html
{% extends 'base.html' %}

{% block title %}List creators{% endblock %}

{% block content %}
<h2 class="text-success">My creators</h2>
<ul>
    {% for creator in creators %}
        <li class="text-success">
            <a class="text-success" href="{% url 'store:store-creator' creator.id %}">
                {{ creator.name }}, phone: {{ creator.phone_number }}, {{ creator.country }}
            </a>
        </li>
    {% empty %}
        <li>For now not free creators.</li>
    {% endfor %}
</ul>
{% endblock %}

storeproject/store/templates/home.html

{% extends 'base.html' %}

{% block title %}Це основна сторінка{% endblock %}

{% block content %}
<h2 class="text-primary">Привіт користувач-це основна сторінка цього сайту де ти можеш
    відпочити від роботи</h2>
<p class="text-primary">Для ознакомлення які тут є templates (шаблони) пропиши /info/</p>
{% endblock %}

storeproject/store/templates/info.html
{% extends 'base.html' %}

{% block title %}This is main webpaig{% endblock %}

{% block content %}
<h2 class="text-warning">Привіт-це шаблон info ,він допоможе тобі дізнатися які шаблони є на цьому сайті</h2>
<p class="text-warning">На цьому сайті є такі шаблони /creators/,/home/,/info/,/creator/1/</p>
{% endblock %}

storeproject/store/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Логін</title>
</head>
<body>
    <h2>Авторизація</h2>

    {% if error %}
        <p style="color:red;">{{ error }}</p>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Увійти</button>
    </form>
</body>
</html>

storeproject/store/templates/register.html
<h2>Register</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
</form>

storeproject/store/templates/videos.html

{% extends 'base.html' %}

{% block title %}Це відео стрінка{% endblock %}

{% block content %}
<iframe width="853" height="480" src="https://www.youtube.com/embed/rQCJLQKTxHA" title="НОВАЯ РТШКА и КАРТА! НОЯБРЬСКОЕ ГЛОБАЛЬНОЕ ОБНОВЛЕНИЕ | MINECRAFT RUSTME, растми" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
{% endblock %}